update 3.1.0

diff --git a/nukedir b/nukedir
--- a/nukedir
+++ b/nukedir
@@ -3,7 +3,7 @@
 set -euo pipefail
 shopt -s inherit_errexit shift_verbose extglob nullglob
 
-declare -r VERSION='3.1.0'
+declare -r VERSION=3.1.0
 declare -r SCRIPT_NAME=nukedir
 
 # --------------------------------------------------------------------------------
@@ -32,7 +32,7 @@ _msg() {
 info()  { ((VERBOSE)) || return 0; >&2 _msg "$@"; }
 warn()  { ((VERBOSE)) || return 0; >&2 _msg "$@"; }
 error() { >&2 _msg "$@"; }
-die()   { (($# > 1)) && error "${@:2}"; exit "${1:-0}"; }
+die()   { (($# > 1)) && error "${@:2}" ||:; exit "${1:-0}"; }
 
 # --------------------------------------------------------------------------------
 # Utility functions
@@ -146,11 +146,11 @@ main() {
                     wait_for_rsync=1 ;;
     -n|--dryrun)    DRY_RUN=1; dryrun=n ;;
     -N|--notdryrun) DRY_RUN=0; dryrun='' ;;
-    -v|--verbose)   VERBOSE=1 ;;
+    -v|--verbose)   VERBOSE+=1 ;;
     -q|--quiet)     VERBOSE=0 ;;
     -r|--rsync-verbose)
                     rsync_verbose+='v' ;;
-    -V|--version)   echo "$SCRIPT_NAME $VERSION"; exit 0;;
+    -V|--version)   echo "$SCRIPT_NAME $VERSION"; return 0;;
     -h|--help)      usage; return 0 ;;
     -[iTwnNvqrVh]*) #shellcheck disable=SC2046 # expand aggregated short options
                     set -- '' $(printf -- "-%c " $(grep -o . <<<"${1:1}")) "${@:2}";;
@@ -160,7 +160,7 @@ main() {
 
   ((${#nuke_dirs[@]})) || die 1 'No directory specified.'
 
-  [[ $PWD == '/' ]] && die 1 'Cannot execute from root directory'
+  [[ $PWD == '/' ]] && die 1 'Cannot execute from root directory'  ||:
 
   rsync_bin=$(command -v rsync) || die 1 'rsync not found'
   if ((ionice)); then
@@ -190,7 +190,7 @@ main() {
     nuke_dir=$(realpath -e "$nuke_dir") || continue
     [[ "$nuke_dir" == '/' ]] && die 1 'ROOT directory CANNOT be specified'
     [[ -d "$nuke_dir" ]] || { error "${nuke_dir@Q} is not a directory"; continue; }
-    is_mount_point "$nuke_dir" && die 1 "Cannot delete a mount point ${nuke_dir@Q}"
+    is_mount_point "$nuke_dir" && die 1 "Cannot delete a mount point ${nuke_dir@Q}" ||:
 
     wait_for_rsync
 
@@ -235,7 +235,7 @@ main() {
     if ((DRY_RUN)); then
       "${rsync_cmd[@]}"
     else
-      "${rsync_cmd[@]}" && rmdir "${nuke_dir:-jUnK}"
+      "${rsync_cmd[@]}" && rmdir "${nuke_dir:-jUnK}" ||:
       # Ensure kernel caches are cleared after deletion
       sync
     fi
